import ora from 'ora';
import chalk from 'chalk';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { getLog, getRepoRoot } from '../core/git.js';
import {
  computeAuthorStats,
  computeRepoSummary,
  computeTimeline,
  getTopChurnFiles,
  WEEKDAYS,
} from '../core/stats.js';
import type { AuthorStats, FileChurn, RepoSummary } from '../types.js';

interface ReportOptions {
  since?: string;
  until?: string;
  output?: string;
  top?: string;
}

export interface ReportInput {
  summary: RepoSummary;
  authors: AuthorStats[];
  timeline: { month: string; count: number }[];
  churn: FileChurn[];
  since?: string;
  until?: string;
  generatedAt: Date;
}

function fmtDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/**
 * Render the Markdown report. Reports get pasted into issues and wikis, so the
 * repository is named by its directory name only, never by its local path.
 */
export function buildReport(input: ReportInput): string {
  const { summary, authors, timeline, churn, since, until, generatedAt } = input;
  const repoName = summary.path.split(/[/\\]/).pop() ?? summary.path;
  const lines: string[] = [];

  lines.push(`# ${repoName} — Repository Report`);
  lines.push('');
  lines.push(
    `Generated by [git-chronicle](https://github.com/Shivansh2904/git-chronicle) on ${fmtDate(generatedAt)}.`
  );
  lines.push('');

  lines.push(`## Summary`);
  lines.push('');
  lines.push(`- **Repository:** ${repoName}`);
  lines.push(`- **Total commits:** ${summary.totalCommits.toLocaleString()}`);
  lines.push(`- **Authors:** ${summary.authors}`);
  lines.push(`- **First commit:** ${fmtDate(summary.dateRange.from)}`);
  lines.push(`- **Latest commit:** ${fmtDate(summary.dateRange.to)}`);
  lines.push(
    `- **Most active day/hour:** ${WEEKDAYS[summary.mostActiveDayOfWeek]} at ${summary.mostActiveHour}:00`
  );
  if (since || until) {
    lines.push(`- **Date filter:** ${since ?? 'beginning'} → ${until ?? 'now'}`);
  }
  lines.push('');

  lines.push(`## Top Authors`);
  lines.push('');
  lines.push(`| # | Author | Commits | Insertions | Deletions | Net | Active Days |`);
  lines.push(`|---|--------|--------:|-----------:|----------:|----:|------------:|`);
  authors.forEach((a, i) => {
    const net = a.insertions - a.deletions;
    const netStr = `${net >= 0 ? '+' : ''}${net.toLocaleString()}`;
    lines.push(
      `| ${i + 1} | ${a.name} | ${a.commits.toLocaleString()} | +${a.insertions.toLocaleString()} | -${a.deletions.toLocaleString()} | ${netStr} | ${a.activeDays} |`
    );
  });
  lines.push('');

  lines.push(`## Commit Timeline`);
  lines.push('');
  lines.push(`| Month | Commits |`);
  lines.push(`|-------|--------:|`);
  timeline.forEach((t) => {
    lines.push(`| ${t.month} | ${t.count.toLocaleString()} |`);
  });
  lines.push('');

  if (summary.topLanguages.length > 0) {
    lines.push(`## Languages`);
    lines.push('');
    lines.push(`| Language | File Changes | Share |`);
    lines.push(`|----------|-------------:|------:|`);
    summary.topLanguages.forEach((l) => {
      lines.push(`| ${l.language} | ${l.fileChanges.toLocaleString()} | ${l.pct}% |`);
    });
    lines.push('');
  }

  if (churn.length > 0) {
    lines.push(`## Top Churned Files`);
    lines.push('');
    lines.push(`| # | File | Changes | Insertions | Deletions |`);
    lines.push(`|---|------|--------:|-----------:|----------:|`);
    churn.forEach((f, i) => {
      lines.push(
        `| ${i + 1} | \`${f.path}\` | ${f.changes.toLocaleString()} | +${f.insertions.toLocaleString()} | -${f.deletions.toLocaleString()} |`
      );
    });
    lines.push('');
  }

  return lines.join('\n');
}

export async function runReport(opts: ReportOptions): Promise<void> {
  const top = parseInt(opts.top ?? '15', 10) || 15;
  const output = opts.output ?? 'git-chronicle-report.md';

  const spinner = ora('Reading git history…').start();
  try {
    const root = await getRepoRoot();
    const commits = await getLog(root, opts.since, opts.until);
    spinner.succeed(`Loaded ${commits.length.toLocaleString()} commits`);

    if (commits.length === 0) {
      console.error(chalk.yellow('No commits found in the selected range.'));
      return;
    }

    const markdown = buildReport({
      summary: computeRepoSummary(commits, root),
      authors: computeAuthorStats(commits).slice(0, top),
      timeline: computeTimeline(commits),
      churn: getTopChurnFiles(commits, top),
      since: opts.since,
      until: opts.until,
      generatedAt: new Date(),
    });

    const outputPath = resolve(process.cwd(), output);
    writeFileSync(outputPath, markdown, 'utf8');
    console.log(chalk.green(`Report written to ${outputPath}`));
  } catch (err) {
    spinner.fail('Report generation failed');
    console.error(chalk.red((err as Error).message));
    process.exit(1);
  }
}
